### ISSUE TITLE
Docs not uploaded for 0.1.1.1

### ISSUE THREAD

**Issue by sir4ur0n** [felixmulder/kafka-client-sync#1]
Hi,

Documentation seems to not have been uploaded for 0.1.1.1, meaning we can't explore it on Hackage:
https://hackage.haskell.org/package/kafka-client-sync-0.1.1.1
![image](https://user-images.githubusercontent.com/1204125/73939744-66a72a80-48ea-11ea-9cc0-23c36423fcf7.png)

While it's available for 0.1.1.0:
https://hackage.haskell.org/package/kafka-client-sync-0.1.1.0
![image](https://user-images.githubusercontent.com/1204125/73939773-745cb000-48ea-11ea-81ac-ff8382992697.png)

Would you mind uploading it (if possible) please? :smile: 

Thank you!

**Comment by felixmulder** [comment]
Ah, but of course! :) Let me get right on that

**Comment by felixmulder** [comment]
That should do it 👏

**Comment by sir4ur0n** [comment]
Thank you kind sir!
